### PR TITLE
[IMP] ir_attachment_url: allow to get url

### PR DESCRIPTION
**Pull request by jjscarafia**
First, thanks for this great module!

With this change it is easy to, for example, export images (urls) and load them on a new database, for eg.
`data = source_db.env['product.template'].export_data(['id', 'image'])`
and then
`target_db.env['product.template'].with_context(attachment_return_url=True).load(['id', 'image'], data['datas'])`

### CODE REVIEW

**Comment by trojikman** [comment]
Hi! Thanks for contribution! 
First of all, could you run the command `pre-commit run --all` in your repository folder to apply hooks to fix code style mismatch or just replace braces how it done there https://github.com/itpp-labs/misc-addons/pull/991/checks?check_run_id=700349832#step:12:115

**Comment by jjscarafia** [comment]
done @trojikman 
Thanks!

**Comment by yelizariev** [comment]
Hola Juan, 

did you mean following usage example?

```

data = source_db.env['product.template'].with_context(attachment_return_url=True).export_data(['id', 'image'])
target_db.env['product.template'].load(['id', 'image'], data['datas'])
```

Thanks for the PR. FYI, we [decided](https://github.com/itpp-labs/misc-addons/pull/984#issuecomment-625084334) to drop support of passing urls to binary field in write methods in odoo 13, cause the module becomes too hacky and has to patch to many code of odoo 13. Though [I'm thinking](https://github.com/itpp-labs/misc-addons/pull/984#discussion_r429750771) about possible API after such refactoring

cc @em230418

**Comment by jjscarafia** [comment]
Hi @yelizariev thanks for the quick response and showing that wip.
So now this module (ir_attachment_url) would be only a base module to be extended by others like the s3 one? Already attache links would continue working with this change? Isn't it?
Have you seen [this](https://gitlab.com/hibou-io/hibou-odoo/suite/-/tree/12.0/attachment_minio) approach of s3 sotorage? Any opinion? Is much simpler, what do you think it would be the downside of such approach?
Thanks!

**Comment by em230418** [comment]
> So now this module (ir_attachment_url) would be only a base module to be extended by others like the s3 one?

Yes.

> Already attache links would continue working with this change?

Not sure. I haven't tested how it will work, 'cos I am working on rewriting ir_attachment_* modules for them to work in 13.0. I will discuss it with @yelizariev 

> Have you seen this approach of s3 sotorage?

Fast-looked that module. Looks like it works with s3 storage files as binary files. The same thing will do ir_attachment_s3 after refactoring but our ir_attachment_s3 with combination ir_attachment_url on http request to odoo instance will return links instead of binary data. Here is usage from documents (not final version): https://github.com/em230418/misc-addons/blob/1f58f58e6065a264d7a1f8e1fe96a8531bfb9181/ir_attachment_url/doc/index.rst

**Comment by yelizariev** [comment]
> So now this module (ir_attachment_url) would be only a base module to be extended by others like the s3 one? Already attache links would continue working with this change? Isn't it?

Correct. Main feature of the ir_attachment_url would be making redirection to storage url on requesting binary fields or attachment via odoo urls (/web/image/... and other)

# About attachment_minio.

> Have you seen this approach of s3 sotorage? Any opinion? Is much simpler, what do you think it would be the downside of such approach?

[That approach](https://gitlab.com/hibou-io/hibou-odoo/suite/-/blob/12.0/attachment_minio/models/ir_attachment.py) requires odoo server to download file from s3 storage and then pass it to the user. 

Pros:

* simple
* solves problem "disk space is out"
* simplifies backuping

Cons:

* increase read time
* Doesn't decrease server load for serving images and files
* doesn't allows to use distributed CDN directly (Though CDN like cloudfront and cloudflare can download content from odoo server and then distribute it, but this scheme looks strange)

**Comment by jjscarafia** [comment]
Thanks you both for the quick and detailed responses. I close the PR because it doesn't make any cense on the new approach.
Thanks!

**Comment by yelizariev** [comment]
I'm not sure that we'll apply new approach in v12, so we potentially can merge this PR

**Review by yelizariev — APPROVED** [review]

**Comment by trojikman** [comment]
@jjscarafia Can you add your copyright at the top of the file?

**Comment by jjscarafia** [comment]
hi @trojikman really needed? no problem for me if no copyright.
But if needed, should I add something like this?
`# Copyright 2020 ADHOC SA <https://www.adhoc.com.ar>`

or personal like this:
`# Copyright 2020 Juan Jose Scarafia <https://github.com/jjscarafia>`

Thanks!

**Comment by trojikman** [comment]
> hi @trojikman really needed? no problem for me if no copyright.

Hi, @jjscarafia. Copyrights are not obligatory and I can merge without it as it is now. The purpose of all this is to indicate your participation in the development of the module :blush:

> But if needed, should I add something like this?
> `# Copyright 2020 ADHOC SA <https://www.adhoc.com.ar>`
> 
> or personal like this:
> `# Copyright 2020 Juan Jose Scarafia <https://github.com/jjscarafia>`

Both variants are suitable :+1:

Best regards!

**Comment by jjscarafia** [comment]
Thanks for protecting contributors ;)
In this case, no problem to don't have me us copyright. 
For now I'm not going to use this functionality. So merge it or cancel it, as you prefer. Thanks!

**Comment by trojikman** [comment]
I approve to merge it now

**Pull request merged**
