### PR TITLE
:arrow_up::one::two: base_attendance

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
After installing the base_attendances module, there is no item "Partner Attendances" on the menu.

**Comment by GabbasovDinar** [comment]
@Ramil-Mukhametzyanov 
image

Access rights
-------------

In order to set access rights for users

* Open menu ``[[ Settings ]] >> Users``
* Click on required user
* Click ``Edit`` and set field **Attendance**:

    * ``Read-Only`` may see only *Attendances* menu
    * ``Manual Attendance`` may create and update partner attendances, but not delete
    * ``Officer`` may also delete partners attendances, has access to *Partners*, *Reports* menus and *Kiosk Mode*
    * ``Manager`` like Officer, but also has access to *Configuration* menu

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
You found it. :+1:

**Review by yelizariev — APPROVED** [review]

**Comment by yelizariev** [comment]
tests doesn't work due to web_website module. @KolushovAlexandr will check it later https://travis-ci.com/it-projects-llc/misc-addons/jobs/160806933

**Pull request merged**
