### PR TITLE
Added string to view field to make the label translatable

### PR DESCRIPTION
**Pull request by sysadminmatmoz**
I noticed, that the label on the form was not translatable

### CODE REVIEW

**Comment by sysadminmatmoz** [comment]
A field string gives the possibility to translate the view label. This commit has only taken care of the reminder_alarm_ids label and their relative translation.

**Comment by yelizariev** [comment]
Ok, thanks.
By the way, do you know why is not possible to translate without this trick?

**Comment by sysadminmatmoz** [comment]
I'm not completely sure, but it has something to do with many2 relations, whenever they're m2o or m2m.

**Comment by yelizariev** [comment]
But they don't use this trick in odoo source. E.g. Tags in project.task is translatable

I think, the issue happens in some combination of many2x with inheritance or using AbstractModel

**Pull request merged**
