### PR TITLE
[FIX][8.0] function with api@multi is already check to one before, an…

### PR DESCRIPTION
**Pull request by sergiocorato**
…d return true instead of name (I think...)

### CODE REVIEW

**Comment by sergiocorato** [comment]
n.b. this mp resolve a bug in getting name
```
`Traceback (most recent call last):
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/simplerp/buildout/parts/SimplERP/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/simplerp/buildout/parts/SimplERP/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/SimplERP/addons/project_issue/project_issue.py", line 326, in write
    return super(project_issue, self).write(cr, uid, ids, vals, context)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/SimplERP/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/misc-addons/reminder_base/reminder_base_models.py", line 157, in write
    self._update_reminder(vals)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/misc-addons/reminder_base/reminder_base_models.py", line 55, in _update_reminder
    r._update_reminder_one(vals)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/misc-addons/reminder_base/reminder_base_models.py", line 74, in _update_reminder_one
    self._do_update_reminder(update_date=self._reminder_date_field in vals)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/misc-addons/reminder_base/reminder_base_models.py", line 79, in _do_update_reminder
    r._do_update_reminder_one(update_date=True)
  File "/opt/simplerp/buildout/parts/SimplERP/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/simplerp/buildout/parts/misc-addons/reminder_base/reminder_base_models.py", line 85, in _do_update_reminder_one
    vals = {'name': self._get_reminder_event_name()[0]}
TypeError: 'bool' object has no attribute '__getitem__'`
```

**Comment by yelizariev** [comment]
Thank you. I applied recently script to fix Lint errors and in introduced this errors. I'll be more carefull about it next time.

As for update. I've added a commit to fix lint warning

`reminder_base/reminder_base_models.py:180: [C8108(method-compute), ReminderAdminWizard] Name of compute method should starts with "_compute_"
`

**Comment by yelizariev** [comment]
@ilmir-k kindly check reminder modules

**Comment by sergiocorato** [comment]
:+1:

**Comment by ilmir-k** [comment]
approved :+1:

**Pull request merged**
