### PR TITLE
web_debranding: fix bytes vs str in regex substitution in web_planner

### PR DESCRIPTION
**Pull request by WohthaN**
Fixes the "Implementation" feature, that was not reacting and producing [1] in the error log.

[1]
```
Traceback (most recent call last):
  File "/opt/zelo/src/main/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/zelo/src/main/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/zelo/src/main/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/zelo/src/main/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/zelo/src/main/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/zelo/src/main/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/zelo/src/main/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/zelo/src/main/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/zelo/src/main/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/zelo/src/active_modules/web/controllers/main.py", line 933, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/zelo/src/active_modules/web/controllers/main.py", line 925, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/zelo/src/main/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/zelo/src/main/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/zelo/src/active_modules/web_debranding/models/web_planner.py", line 25, in render
    res = re.sub(rb'<img src="/web_planner/static/src/img/odoo_logo.png"/>', '', res)
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected a bytes-like object, str found

```

### CODE REVIEW

**Comment by yelizariev** [comment]
@Railia please confirm the issue and the fix

**Comment by mariusmarolla** [comment]
Hi guys!
Verified the same issue... Fix seems to work flowlessly...
Any news about the pr?

**Comment by WohthaN** [comment]
ping

**Comment by yelizariev** [comment]
Sorry for delay, we expect to check it soon

**Review by Railia — APPROVED** [review]

**Comment by WohthaN** [comment]
Thanks!

**Pull request merged**
