### PR TITLE
:arrow_up::one::two: ir_config_parameter_multi_company

### PR DESCRIPTION
**Pull request by KolushovAlexandr**

### CODE REVIEW

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
An error occurs if I try to create a new parameter in System Parameters

**Review by yelizariev — APPROVED** [review]
code looks fine

**Comment by yelizariev** [comment]
```
Traceback (most recent call last):
`   File "/home/travis/build/it-projects-llc/misc-addons/ir_config_parameter_multi_company/tests/test_base.py", line 37, in test_cache
`     self.assertEqual(self.config_param.get_param(KEY), VALUE1)
` AssertionError: 'value2' != 'value1'
` - value2
` ?      ^
` + value1
` ?      ^
` 
FAILED
```

**Comment by yelizariev** [comment]
```

2018-11-16 09:59:04,511 4780 INFO openerp_test odoo.addons.web_website.tests.test_website_dependent: Default, company-specific and website-specific values, record test.website_dependent(6,)
2018-11-16 09:59:04,612 4780 WARNING openerp_test odoo.models: Comparing apples and oranges: res.users(1,) == 1 (/home/travis/odoo-11.0/odoo/models.py:4708)
```

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
Good

**Pull request merged**
