### PR TITLE
:bomb: fix work id

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by yelizariev** [comment]
How to reproduce the error that this update fix?

**Comment by GabbasovDinar** [comment]
@yelizariev When the timer counts down 2 hours, the server timer does not stop automatically due to a task ID error. The timer stops only after running the cron function

**Comment by yelizariev** [comment]
Please update changelog and version

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
If the subtask stops, its counter stops as appropriate.

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
Need to reload the page to see the following changes:
•	Clicking on the subtask counter does not cause this counter to be paused. 
•	After creating a new subtask and running it, the counter is not updated. The counter does not change its behavior even if the subtask is paused.
•	 If another subtask is running, the subtask cannot be run after the run button is wrongly pressed.

**Comment by yelizariev** [comment]
@GabbasovDinar add @Ramil-Mukhametzyanov's comments to README as TODOs or fix them

**Comment by GabbasovDinar** [comment]
@yelizariev @Ramil-Mukhametzyanov I cannot reproduce the error

**Review by Ramil-Mukhametzyanov — COMMENTED** [review]
I saw this bug again in a new build with updates and explicit modules.
It began when I clicked on the counters.
The problem disappeared after second entry in the pull through runbot.

**Comment by GabbasovDinar** [comment]
@Ramil-Mukhametzyanov Maybe the problem is related to the error of the work of longpolling in the runbot. I don't have the error on my server

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
The main changes are verified.
It is difficult to reproduce errors with displaying counters on the runbot.

**Pull request merged**
