### PR TITLE
10.0 ir attachment s3 mini images

### PR DESCRIPTION
**Pull request by yelizariev**

### CODE REVIEW

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
The main goal is achieved, but there are new errors:
1. Fail to replace product image uploading the new image
2. Error 'Incorrect padding' appears when trying to convert product image to an image via link
3. If the newly created image is set through the URL, the image is not displayed.

**Comment by yelizariev** [comment]
1. it's browser cache problem. Try the same scenario without module
2. What do you mean? White Border of the image? Try the same scenario without module
3. Clarify steps to reproduce please

**Comment by Ramil-Mukhametzyanov** [comment]
>     1. it's browser cache problem. Try the same scenario without module

If I try to change the product image by following the steps below, changing the image will fail:
Edit product->Click upload :file_folder: button ->Select image->Click Save.
I need to delete the image and save the product, then upload new image to succeed.
Ok, this is not a bug.

**Comment by Ramil-Mukhametzyanov** [comment]
>     2. What do you mean? White Border of the image? Try the same scenario without module
>     3. Clarify steps to reproduce please

The same issue is being fixed here:
https://github.com/it-projects-llc/misc-addons/pull/674
We need to create another pull-requests to repair ir_attachment_url for Odoo 10.0 and 11.0.

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
Finally， there are no related issues.

**Pull request merged**
