### PR TITLE
fix(web_debranding): no more bytes returned

### LINKED ISSUE #762: Web Debranding Decode Issue
How do you address this decode error:
ir_translation.py AttributeError: 'str' object has no attribute 'decode' - - -

I believe this is a migration issue to Python3?
def debrand_bytes(env, source):
    return bytes(debrand(env, source.decode('utf-8')), 'utf-8')

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/75591286-web-debranding-decode-issue?utm_campaign=plugin&utm_content=tracker%2F2288638&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F2288638&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by blaggacao**
Closes #762 
Replaces #719

### CODE REVIEW

**Comment by blaggacao** [comment]
Break... this is not the solution
from: https://docs.python.org/3.5/library/xml.etree.elementtree.html
```help
Generates a string representation of an XML element, including all subelements. element is an Element instance. encoding [1] is the output encoding (default is US-ASCII). Use encoding="unicode" to generate a Unicode string (otherwise, a bytestring is generated). method is either "xml", "html" or "text" (default is "xml"). short_empty_elements has the same meaning as in ElementTree.write(). Returns an (optionally) encoded string containing the XML data.
```

**Comment by blaggacao** [comment]
Ok, this is the correct solution, but it exposes an underlying odoo bug, which I will solve in a second... please help accepting.

**Review by yelizariev — APPROVED** [review]
Should be ok if it works :)

**Comment by blaggacao** [comment]
Here is the PR: https://github.com/odoo/odoo/pull/34751
The commit: https://github.com/odoo/odoo/pull/34751/commits/5a8c31ac1af31dd13626f83435d4b818398c26ab

**Comment by blaggacao** [comment]
Patch is here: https://patch-diff.githubusercontent.com/raw/odoo/odoo/pull/34751.patch

**Comment by blaggacao** [comment]
CI Failure due to upstream patch not applied...

**Review by yelizariev — CHANGES_REQUESTED** [review]
I need to block this:

* The PR has to be merged
* We need to update documentation to say that it works for latest version only or with the patch applied

I'd prefer to merge this in odoo 13 instead where all users have the patch for sure

**Comment by blaggacao** [comment]
Okk, I assume odoo might merge the fix and forward port the patch... I hope... You could upvote...

**Comment by blaggacao** [comment]
So this has been merged: https://github.com/odoo/odoo/pull/34751 Now we can look over this again from a new perspective, I guess the fix became obsolete, now.

**Comment by blaggacao** [comment]
It looks like this is obsolete now, and byte is the expected return value from 11.0 onwards.

**Comment by blaggacao** [comment]
@yelizariev This is the correct fix now that the upstream patch coerces to bytes...

**Comment by blaggacao** [comment]
From travis:
```
  File "/home/travis/build/it-projects-llc/misc-addons/web_debranding/controllers/main.py", line 84, in qweb
    content = debrand(request.session.db and request.env or None, content)
```

after the fix this line ought to be:
```python
content = debrand_bytes(request.session.db and request.env or None, content)
```

**Comment by blaggacao** [comment]
My bad

**Pull request closed without merging**
