### PR TITLE
11.0 merge 41cc944 expiration date

### PR DESCRIPTION
**Pull request by yelizariev**

### CODE REVIEW

**Comment by yelizariev** [comment]
lint errors for `web_debranding` and `theme_kit` will be fixed in 10.0 branch

**Comment by yelizariev** [comment]
@Railia check modules with code-related updates (i.e. you can exclude doc updates, translation etc)

**Review by Railia — CHANGES_REQUESTED** [review]
I got issue when I uninstalled ir_config_parameter_multicompany (S3 module wasn't uninstalled)

**Review by Railia — CHANGES_REQUESTED** [review]
@iledarn Please solve all conflicts

**Review by Railia — APPROVED** [review]

**Comment by yelizariev** [comment]
@iledarn the error happened again
```

` AssertionError: ('Error loading file http://127.0.0.1:8069/web/static/lib/nvd3/nv.d3.js\n'
`  ' at http://127.0.0.1:8069/web/content/514-3759b4f/web.assets_common.js:3848 '
`  '(in onerror)\n'
```

**Pull request merged**
