### PR TITLE
[10.0][FIX] Fix js assets missing in res_partner_skype

### PR DESCRIPTION
**Pull request by robyf70**
This fixes the missing assets on res_partner_skype module. I've also renamed \_\_openerp\_\_ to \_\_manifest\_\_

### CODE REVIEW

**Comment by yelizariev** [comment]
It seems that removing 'js' section from manifest is correct, but we don't need to add assets, because the same in data.xml file
https://github.com/it-projects-llc/misc-addons/blob/10.0/res_partner_skype/data.xml

**Comment by robyf70** [comment]
Right! Should I update the patch?

**Comment by yelizariev** [comment]
Yes, just remove js section in this PR and I will merge it

**Comment by yelizariev** [comment]
I mean let this PR only removes js section and doesn't add assets file

**Comment by robyf70** [comment]
Ok! I've push just now the changes

**Comment by yelizariev** [comment]
Thank you

**Pull request merged**
