### PR TITLE
11.0 port ir attachment s3

### PR DESCRIPTION
**Pull request by iledarn**

### CODE REVIEW

**Comment by ilmir-k** [comment]
@iledarn fix the lints please

**Comment by ilmir-k** [comment]
@yelizariev we need to merge it
the tests can be done later

**Comment by yelizariev** [comment]
Url doesn't work when I insert following url to User Image: https://avatars1.githubusercontent.com/u/14071718?s=88&v=4

**Comment by yelizariev** [comment]
It doesn't work with normal urls either:
https://static.pexels.com/photos/20787/pexels-photo.jpg
```


Error:
Odoo Server Error

Traceback (most recent call last):
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/addons/base/res/res_users.py", line 808, in write
    res = super(UsersView, self).write(values)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/addons/base/res/res_users.py", line 646, in write
    res = super(UsersImplied, self).write(values)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/addons/base/res/res_users.py", line 351, in write
    res = super(Users, self).write(values)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/models.py", line 3155, in _write
    self.env[parent_model].browse(parent_ids).write(parent_vals)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/addons/base/res/res_partner.py", line 514, in write
    result = result and super(Partner, self).write(vals)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/models.py", line 3133, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/fields.py", line 1704, in write
    atts.write({'datas': value})
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/addons/base/ir/ir_attachment.py", line 409, in write
    vals = self._check_contents(vals)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/addons/base/ir/ir_attachment.py", line 242, in _check_contents
    mimetype = values['mimetype'] = self._compute_mimetype(values)
  File "/mnt/odoo-extra/runbot/static/build/12051-495-33cec7/odoo/addons/base/ir/ir_attachment.py", line 238, in _compute_mimetype
    mimetype = guess_mimetype(base64.b64decode(values['datas']))
  File "/usr/lib/python3.4/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Comment by yelizariev** [comment]
@iledarn This branch has conflicts that must be resolved

**Comment by yelizariev** [comment]
Issues about missing tests: #515 #509

**Comment by yelizariev** [comment]
В 11й версии есть новый параметр crop, который пропустили https://github.com/odoo/odoo/commit/2e3848b394748bf23eff0db0d6d92b9e8c9bf875

**Pull request merged**
