### PR TITLE
11.0 merge 9872fe8 csrf issue

### PR DESCRIPTION
**Pull request by yelizariev**

### CODE REVIEW

**Comment by yelizariev** [comment]
@Railia 
this PR can be merged only via **Create Merge Commit**

**Review by Railia — CHANGES_REQUESTED** [review]
@yelizariev I've got the error when database.secret values were removed from System Parameters(for the 1st company) and Company Properties (for the 2nd company). See screenshot:
screenshot-15120-570-fa05b8-base runbot it-projects info-2018 03 30-12-06-28

**Comment by yelizariev** [comment]
Thank you @Railia 
It's fixed

**Review by Railia — APPROVED** [review]

**Review by ilmir-k — APPROVED** [review]
:+1:

**Pull request merged**
