### PR TITLE
FIX requires which is changed in odoo 11

### PR DESCRIPTION
**Pull request by KomarovAlea**
Old code was wrong and take error. Look at you browser console when you load odoo 11.
I fixed this code and tested it. New code is work fine.

### CODE REVIEW

**Comment by KolushovAlexandr** [comment]
Hi @KomarovAlea Thanks for contributing, but this module isn't even installable https://github.com/it-projects-llc/misc-addons/blob/11.0/web_polymorphic_field/__openerp__.py#L31. I've checked your changes with product_details and caught a bug. In all our modules that depend on the web_polymorphic_field, we refused from that dependency now. @yelizariev PR may be closed.

**Comment by KomarovAlea** [comment]
>  I've checked your changes with product_details and caught a bug. 

I checked new code and it's worked. What error did you find in my code?
I get a Project with modules which depends from web_polymirphic_field and I have to continue support them. If my code contain bug then I have to fixed them.

**Comment by KolushovAlexandr** [comment]
http://misc.odoo11.local/web/static/src/js/fields/abstract_field.js:99
Traceback:
TypeError: Cannot read property 'fields' of undefined
    at Class.init (http://misc.odoo11.local/web/static/src/js/fields/abstract_field.js:99:29)
    at Class.prototype.(anonymous function) [as init] (http://misc.odoo11.local/web/static/src/js/core/class.js:90:38)
    at Class.init (http://misc.odoo11.local/web/static/src/js/fields/relational_fields.js:2048:21)
    at Class.prototype.(anonymous function) [as init] (http://misc.odoo11.local/web/static/src/js/core/class.js:90:38)
    at Class.init (http://misc.odoo11.local/web_polymorphic_field/static/src/js/view_form.js:24:18)
    at Class.prototype.(anonymous function) [as init] (http://misc.odoo11.local/web/static/src/js/core/class.js:90:38)
    at new Class (http://misc.odoo11.local/web/static/src/js/core/class.js:107:33)
    at Class._renderFieldWidget (http://misc.odoo11.local/web/static/src/js/views/basic/basic_renderer.js:532:22)
    at Class._renderTagField (http://misc.odoo11.local/web/static/src/js/views/form/form_renderer.js:573:21)
    at Class._renderNode [as _super] (http://misc.odoo11.local/web/static/src/js/views/form/form_renderer.js:483:29)

I just tried to open a form with a polymorphic widget

**Review by KolushovAlexandr — CHANGES_REQUESTED** [review]
by the reason written above

**Pull request closed without merging**
