### PR TITLE
remove about odoo link

### PR DESCRIPTION
**Pull request by igallyamov**
Удаляет ссылку About Odoo в верхнем меню справа

### CODE REVIEW

**Comment by sysadminmatmoz** [comment]
I think you should consider to restore at least the debug mode activation link which was under that link.

**Comment by yelizariev** [comment]
@sysadminmatmoz you can activate developer mode manually by adding ?debug to url

**Comment by sysadminmatmoz** [comment]
I know that @yelizariev :) I meant just (to keep it developer friendly too) to leave the actual link. Instead of removing the about odoo link, just replace it with the said (?debug) link.

**Comment by yelizariev** [comment]
@sysadminmatmoz ,
Debug mode link instead of "About odoo" is extra unnecessary item for usual user.
We can hide debug menu somewhere deeper, but it  becomes easier to add ?debug manually.

**Comment by sysadminmatmoz** [comment]
@yelizariev 
I did some thinking about it and I have to agree with you. The option was not intended for an average user, so disregard my former comments.

**Pull request merged**
