### PR TITLE
[11.0][PORT] _auto_end is not available in 11.0

### PR DESCRIPTION
**Pull request by yelizariev**

### CODE REVIEW

**Comment by yelizariev** [comment]
@ursus102 see doc/index.rst for usage instruction

**Comment by ursus102** [comment]
An error occurred in the Default Values section (ir_config_parameter_multi_company / doc / index.rst):
Then for companyA we have
param1 = value11 (value for companyA)
...
Then for **companyA** we have 

Should be:
Then for company**B** we have

**Comment by ursus102** [comment]
An error occurred in the Configuration section (ir_config_parameter_multi_company / doc / index.rst):

>Open menu [[ Settings ]] >> General Settings

There is no default General Settings menu

> First you need to install the Initial Setup Tools

**Comment by ursus102** [comment]
An error occurred in the Configuration section (ir_config_parameter_multi_company / doc / index.rst):

> Open menu [[ Settings ]] >> Users >> Users
Select your user
Add some companies to Allowed Companies field

There is no default field **Allowed Companies**

**Comment by yelizariev** [comment]
Company reference is fixed at 10.0 and will be merged here later
https://github.com/it-projects-llc/misc-addons/commit/95088240f0636096953c04f490ae9329c8655500

**Comment by yelizariev** [comment]
**Allowed Companies** field will be visible after activating Multi-Company in General Settings

**Comment by ursus102** [comment]
> Allowed Companies field will be visible after activating Multi-Company in General Settings

And if there are more than one line in the list of Companies

**Comment by ursus102** [comment]
The case is not covered:

System Parameters
default: create param_2 = value_2

then change param_2 - rename to param_21 and:
YourCompany
param_21 = value_21
SecondCompany
param_21 = value_2

Then we find this records in Company Properties:
param_21 is absent, just param_2
and value for param_2:
YourCompany param_2 = value_2
SecondCompany param_2 = value_2

Where is param_21 in Company Properties, and why param_2 for YourCompany != value_21

**Comment by ursus102** [comment]
An error occurred in the Uninstallation section (ir_config_parameter_multi_company / doc / index.rst):

> Click [Validate] -- it must not return errors!

1. [Validate] - [Test Import]

2. After pressing Test Import, the process ended with a disconnection. Verification failed

3. After uninstal module ir_config_parameter_multi_company the server disable whith error:

> Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by yelizariev** [comment]
I found some logs:

2017-11-10 09:05:05,704 1557 INFO 10732-494-0efe07-all werkzeug: 127.0.0.1 - - [10/Nov/2017 

```
09:05:05] "POST /web/dataset/call_kw/res.users/check_access_rights HTTP/1.0" 200 -
2017-11-10 09:05:05,709 1558 INFO 10732-494-0efe07-all werkzeug: 127.0.0.1 - - [10/Nov/2017 09:05:05] "POST /web/dataset/call_kw/ir.model.data/xmlid_to_res_id HTTP/1.0" 200 -
2017-11-10 09:05:05,719 1557 INFO 10732-494-0efe07-all werkzeug: 127.0.0.1 - - [10/Nov/2017 09:05:05] "POST /web/dataset/call_kw/ir.ui.view/check_access_rights HTTP/1.0" 200 -
2017-11-10 09:05:09,208 1558 INFO 10732-494-0efe07-all werkzeug: 127.0.0.1 - - [10/Nov/2017 09:05:09] "POST /web/dataset/call_kw/base.module.uninstall/create HTTP/1.0" 200 -
2017-11-10 09:05:09,607 1557 INFO 10732-494-0efe07-all werkzeug: 127.0.0.1 - - [10/Nov/2017 09:05:09] "POST /web/dataset/call_kw/base.module.uninstall/read HTTP/1.0" 200 -
2017-11-10 09:05:09,984 1557 INFO 10732-494-0efe07-all werkzeug: 127.0.0.1 - - [10/Nov/2017 09:05:09] "POST /web/dataset/call_kw/ir.module.module/read HTTP/1.0" 200 -
2017-11-10 09:05:10,398 1557 INFO 10732-494-0efe07-all odoo.addons.base.module.module: ALLOW access to module.button_immediate_uninstall on [u'ir_config_parameter_multi_company'] to user admin #1 via 127.0.0.1
2017-11-10 09:05:10,398 1557 INFO 10732-494-0efe07-all odoo.addons.base.module.module: User #1 triggered module uninstallation
2017-11-10 09:05:10,398 1557 INFO 10732-494-0efe07-all odoo.addons.base.module.module: ALLOW access to module.button_uninstall on [u'ir_config_parameter_multi_company'] to user admin #1 via 127.0.0.1
2017-11-10 09:05:10,422 1557 INFO 10732-494-0efe07-all odoo.modules.loading: loading 1 modules...
2017-11-10 09:05:10,454 1557 INFO 10732-494-0efe07-all odoo.modules.loading: 1 modules loaded in 0.03s, 0 queries
2017-11-10 09:05:10,612 1557 INFO 10732-494-0efe07-all odoo.modules.loading: updating modules list
2017-11-10 09:05:10,615 1557 INFO 10732-494-0efe07-all odoo.addons.base.module.module: ALLOW access to module.update_list on [] to user admin #1 via 127.0.0.1
2017-11-10 09:05:13,009 1557 INFO 10732-494-0efe07-all odoo.modules.loading: loading 16 modules...
2017-11-10 09:05:13,044 1557 INFO 10732-494-0efe07-all odoo.modules.loading: 16 modules loaded in 0.03s, 0 queries
2017-11-10 09:05:13,140 1557 INFO 10732-494-0efe07-all odoo.models.unlink: User #1 deleted ir.property records with IDs: [1, 2, 3, 4, 5, 6, 7, 8]
2017-11-10 09:05:13,144 1557 INFO 10732-494-0efe07-all odoo.addons.base.module.module: ALLOW access to module.module_uninstall on [u'ir_config_parameter_multi_company'] to user admin #1 via 127.0.0.1
2017-11-10 09:05:13,159 1557 INFO 10732-494-0efe07-all odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [4060]
2017-11-10 09:05:13,179 1557 INFO 10732-494-0efe07-all odoo.modules.loading: Reloading registry once more after uninstalling modules
2017-11-10 09:05:13,197 1557 INFO 10732-494-0efe07-all odoo.modules.loading: loading 1 modules...
2017-11-10 09:05:13,234 1557 INFO 10732-494-0efe07-all odoo.modules.loading: 1 modules loaded in 0.04s, 0 queries
2017-11-10 09:05:13,307 1558 INFO ? werkzeug: 127.0.0.1 - - [10/Nov/2017 09:05:13] "GET /web/static/src/img/spin.png HTTP/1.0" 200 -
2017-11-10 09:05:13,408 1557 INFO 10732-494-0efe07-all odoo.modules.loading: updating modules list
2017-11-10 09:05:13,412 1557 INFO 10732-494-0efe07-all odoo.addons.base.module.module: ALLOW access to module.update_list on [] to user admin #1 via 127.0.0.1
2017-11-10 09:05:14,767 1557 INFO 10732-494-0efe07-all odoo.modules.loading: loading 15 modules...
2017-11-10 09:05:14,798 1557 INFO 10732-494-0efe07-all odoo.modules.loading: 15 modules loaded in 0.03s, 0 queries
2017-11-10 09:05:14,978 1557 INFO 10732-494-0efe07-all odoo.modules.loading: Modules loaded.
2017-11-10 09:05:14,981 1557 INFO 10732-494-0efe07-all odoo.addons.base.module.module: getting next ir.actions.todo()
2017-11-10 09:05:14,984 1557 INFO 10732-494-0efe07-all odoo.modules.registry: Registry changed, signaling through the database
2017-11-10 09:05:14,985 1557 INFO 10732-494-0efe07-all werkzeug: 127.0.0.1 - - [10/Nov/2017 09:05:14] "POST /web/dataset/call_button HTTP/1.0" 200 -
2017-11-10 09:05:15,303 1557 INFO 10732-494-0efe07-all odoo.addons.base.ir.ir_http: Generating routing map
2017-11-10 09:05:15,547 1557 ERROR 10732-494-0efe07-all odoo.sql_db: bad query: SELECT "ir_config_parameter"."id" as "id","ir_config_parameter"."value" as "value" FROM "ir_config_parameter" WHERE "ir_config_parameter".id IN (2)
ERROR: column ir_config_parameter.value does not exist
LINE 1: SELECT "ir_config_parameter"."id" as "id","ir_config_paramet...
                                                  ^

2017-11-10 09:05:15,841 1557 INFO 10732-494-0efe07-all werkzeug: 127.0.0.1 - - [10/Nov/2017 09:05:15] "GET /web?debug=1 HTTP/1.0" 500 -
2017-11-10 09:05:15,890 1557 ERROR 10732-494-0efe07-all werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/http.py", line 1298, in __call__
    return self.dispatch(environ, start_response)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/http.py", line 1473, in dispatch
    result = ir_http._dispatch()
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/http.py", line 761, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/http.py", line 820, in dispatch
    r = self._call_function(**self.params)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/addons/web/controllers/main.py", line 449, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/addons/web/models/ir_http.py", line 18, in webclient_rendering_context
    'session_info': json.dumps(self.session_info()),
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/addons/web_tour/models/ir_http.py", line 12, in session_info
    result = super(Http, self).session_info()
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/addons/web/models/ir_http.py", line 40, in session_info
    "web.base.url": self.env['ir.config_parameter'].sudo().get_param('web.base.url', default=''),
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/addons/base/ir/ir_config_parameter.py", line 60, in get_param
    return self._get_param(key) or default
  File "<decorator-gen-34>", line 2, in _get_param
    
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/addons/base/ir/ir_config_parameter.py", line 65, in _get_param
    params = self.search_read([('key', '=', key)], fields=['value'], limit=1)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/models.py", line 4135, in search_read
    result = records.read(fields)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/models.py", line 2506, in read
    self._read_from_database(stored, inherited)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/models.py", line 2625, in _read_from_database
    cr.execute(query_str, params)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/10732-494-0efe07/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column ir_config_parameter.value does not exist
LINE 1: SELECT "ir_config_parameter"."id" as "id","ir_config_paramet...
                                                  ^
2017-11-10 09:05:53,798 1560 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'dbname=10732-494-0efe07-base host=172.17.0.2 user=odoo sslmode=prefer password=xxxx port=5432'
2017-11-10 09:05:53,819 1560 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'dbname=10732-494-0efe07-all host=172.17.0.2 user=odoo sslmode=prefer pa
```

**Comment by yelizariev** [comment]
Seems that uninstalling process is changed in 11.0 and we need to update ``base`` module automatically. 
I will check that. Such update may be useful in 10.0 too -- no need to ask user to update ``base`` module.

Also, I will check is it possible to make full deintallation process automatic. So, user would just click "Uninstall" and nothing else

**Review by ursus102 — CHANGES_REQUESTED** [review]
Again, after uninstal module ir_config_parameter_multi_company the server disable whith error:

    Internal Server Error
    The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Pull request merged**
