### PR TITLE
[FIX] booking_calendar: allow several weekdays bookings

### PR DESCRIPTION
**Pull request by iledarn**

### CODE REVIEW

**Comment by ilmir-k** [comment]
Ivan @yelizariev , updates are working, but it can not be merged due to runbot error

**Comment by ilmir-k** [comment]
@iledarn 
It needs to be fixed for merging:
```
File "/mnt/odoo-extra/runbot/static/build/02065-333-d2b3ef/openerp/models.py", line 5274, in _browse
    env.prefetch[cls._name].update(ids)
TypeError: unhashable type: 'list'
```

**Comment by ilmir-k** [comment]
the same error was here https://github.com/it-projects-llc/misc-addons/pull/308

**Comment by yelizariev** [comment]
You need fix this

```
2016-12-12 10:44:09	WARNING	server	openerp.models:753 _constraint_methods method sale.order.line._check_date_fit_product_calendar: @constrains parameter 'calendar_id' is not stored
2016-12-12 10:44:25	WARNING	server	openerp.models:753 _constraint_methods method sale.order.line._check_date_fit_product_calendar: @constrains parameter 'calendar_id' is not stored
```

**Comment by yelizariev** [comment]
@ilmir-k check, squash and merge

**Pull request merged**
